dist: bionic
os: linux
language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=master

install: pip install tox-travis coveralls
script:
  - tox
after_success: coveralls

jobs:
  include:
    - stage: deploy
      python: 3.7
      deploy:
        provider: pypi
        username: "radico"
        password:
          secure: UX5gnwcP6MpSgxfcoYCj7rBiZMHvVjc0NTKgc5pAUZhACJL/iJ074NgtsntDQRn5hm4/ppRMTQfO4a1LJHLA4OiUAQj2cY0ejDijPPPY9zkbtcJnzIIg+gdo45ASGVdJYQOFTzWU1O0HqBRWXMtEDS34nljiESFJ5numPb34ExY+jmU1ZrCUjy6FwSD/WLNpdGQD6l2jS5GlcH7Wog8vnqHj6+BbTaYX8TeODwh9DJRKdHyGk7+hWAAQIYlI5J/XSkw36jDYvxO0UHZbYBX5cW9RUtFlvjwqRBZp0AAFJ6m8Y6isDHWSS0fzkCcvQ2krhrZ7ttY11QyV8vTiP3j4Z+aH8BlEw+yRcnM0KPexllDeHcwrxNzDNOA3R1p6UhfE+lAtJCPhNT3mn6gvuSXCQZbcWHoRW4KJZE/aIu2FNh6vE1r8UfqsipUUwV2MWJEDeAPaUMtiPisUmBdlJjGZ+EPB4VGzeefyNzlWlF0gkYfxq0cO93N4q6JokQuJ3b7gx6uYeM4i9QGueiR4XiIGRP+WYQX4XRyQ5rm3sGQ9R8oaq7lj7c7Vm7/VBEkj9BEXIVao5LIFBBocOUkOoe727JQIgz/oHRJZz+4HvVifVtR0w26w4mkvZeh8Cv8LNLsuiWJ6dpqBJS1xk53PLxRu/pRslC3e6HTV8I8rPQIXPMg=
        on:
          tags: true
