dist: bionic
os: linux
language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=master
  - REPO_TOKEN=${REPO_TOKEN}
  - PYPITOKEN=${PYPITOKEN}

install: pip install tox-travis coveralls
script:
  - tox
after_success: coveralls

jobs:
  include:
    - stage: deploy
      python: 3.7
      deploy:
        provider: pypi
        username: "__token__"
        password: ${PYPITOKEN}
        on:
          tags: true
