dist: bionic
sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=master
  - REPO_TOKEN=${REPO_TOKEN}
install: pip install tox-travis coveralls
script:
  - tox
after_success: coveralls
