[tox]
envlist =
    py310-django{42, 50, 51, 52}
    py311-django{42, 50, 51, 52}
    py312-django{42, 50, 51, 52, main}
    py313-django{42, 50, 51, 52, main}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv:docs]
allowlist_externals =
    make
deps =
    -rdocs/source/requirements.txt
    Sphinx
changedir = docs
commands =
    make html

[testenv:flake8]
deps = flake8
commands = flake8 comment

[testenv]
deps =
    coverage
    pillow
    pytz
    djangorestframework
    lxml
    beautifulsoup4
    cssselect
    django42: Django>=4.2,<4.3
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
    djangomain: https://github.com/django/django/archive/main.tar.gz

extras =
    markdown

usedevelop = True

commands =
    python manage.py compilemessages -l test
    python -W error::DeprecationWarning -W error::PendingDeprecationWarning -m coverage run --parallel-mode manage.py test {posargs}

setenv =
    PYTHONDONTWRITEBYTECODE=1
    DJANGO_SETTINGS_MODULE=test.settings.test

[testenv:py310-djangomain]
ignore_outcome = true

[testenv:py311-djangomain]
ignore_outcome = true

[testenv:py312-djangomain]
ignore_outcome = true

[testenv:py313-djangomain]
ignore_outcome = true
