# Generated by Django 3.0.5 on 2020-05-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile_userprofile',
        ),
    ]
