name: Linters

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Ensure latest setuptools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependecies
        run: |
            python -m pip install flake8

      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8 comment
